import Head from 'next/head';
import { FC } from 'react';

type propsType = {};

const DefaultHead: FC<propsType> = () => {
  return (
    <Head>
      <title>My practice</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default DefaultHead;
